baseURL = "http://notsoformal.xyz"
languageCode = "en-us"
title = "Not So Formal"
theme = "minimal-bootstrap-hugo-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  description = "Applied data science breadcrumbs"
  contentBackgroundColor = "#ffffff"
  contentTextColor = "#000"
  contentLinkColor = "#000"
  contentLinkHoverColor = "#E71D36"
  navbarBackgroundColor = "transparent"
  navbarLinkColor = "#000"
  navbarLinkHoverColor = "#E71D36"
  wrapperMaxWidth = "960px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  # googleAnalytics = "UA-123456789-1"
  cookieConsent = false
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"
  highlightjsTheme = "github-gist"

[menu]
  [[menu.nav]]
  name = "~home"
  url = "/"
  weight = 1

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
