---
title: Map + Reduce in Purrr
author: Thomas Jc
date: '2018-10-31'
slug: map-reduce-in-purrr
categories:
  - rstats
tags:
  - purrr
editor_options: 
  chunk_output_type: console
---

Say you have a list which tells you what is y at x. You intend to manipulate y based on certain condition of x.

For example, given 

```{r}
# here x = year, y = some value
(some_list <- list(
    "year1" = 60,
    "year2" = 70,
    "year3" = 75,
    "year4" = 80,
    "year5" = 100
))
```

What is the cumulative sum of y at year 1, 3, 5? 

In R, it seems natural to do it in a data frame.

```{r, message=FALSE}
library(dplyr)

# first convert to data frame
df <- unlist(some_list) %>% as.data.frame()

# assign a column name
names(df) <- "y"

# calc cumulative sum
df %>% mutate(cum_y = cumsum(y))
```

There is another convenient way to complete the same job.

```{r}
# what we have
some_list

# what we want
cum_x <- c(1, 3, 5)

library(purrr)

# essentially a double loop
map(cum_x, function(x) {
    # here 'map' extracts the component from list (x[1], x[2], ...)
    # and reduce using function 'sum'
    reduce(map(1:x, ~ some_list[[.x]]), sum)
})
```


