---
title: Wrangling Messy Data for D3 Time Series
author: Thomas Jc
date: '2020-02-25'
slug: wrangling-messy-data-for-d3
categories: []
tags: 
    - dplyr
    - json
publishdate: '2020-02-25'
lastmod: '2020-02-25'
---

This is a walkthrough how I transform a dataset to be used in D3. In the process I also export a copy of 'tidy format' for EDA purposes. The dataset is about electric car sales in US from year 2005 to 2017. Origianl data format.  

```{r conf, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(kableExtra)

filepath = "../etc/vehicle-sales/vehicle_sales_data.csv"

filepath %>% 
    read_csv(col_names = FALSE) %>% 
    head() %>% 
    `[`(1:6) %>% 
    kable("html") %>% 
    kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>% 
    row_spec(1:3, bold = T, color = "black", background = "#F4FFE8")
```

The data format I would like to feed to D3 is in JSON and looks like

```json
[{
    "2005-01-01": {
        "Car Model X": {
            "brand": ABC,
            "model": 001,
            "type": "HEV",
            "sales": 99
        },
        "Car Model Y": {
            "brand": DEF,
            "model": 001,
            "type": "HEV",
            "sales": 99
        },
        ...
    } // date as first-level
}]
```
----

### 1 Import 

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(kableExtra)

# this is our column name
carnames   <- read_csv(filepath, col_names = FALSE, n_max = 3) %>% column_to_rownames("X1")

# this is our data
raw        <- read_csv(filepath, col_names = FALSE, skip = 3) %>% column_to_rownames("X1")

# loop through each column and form full car brand
names(raw) <- apply(carnames, 2, paste0, collapse = "-")
head(raw)[1:3] %>% 
    kable("html") %>% 
    kable_styling(position = "center")
```

### 2 Transform 

```{r}
# this is our tidy data
df <- raw %>%
    rownames_to_column("date") %>%
    mutate(date = paste0(date, "-01"),
           date = as.Date(date)) %>% 
    gather(fullname, sales, -date) %>% 
    mutate(brand = str_extract(fullname, "^\\w+"), 
           model = str_extract(fullname, "(?<=-)\\w+(?=-)"),
           type  = str_extract(fullname, "\\w+$")) %>% 
    as_tibble() %>% 
    # column arrangement
    select(-sales, everything(), -fullname)

# preview
df %>% 
    head() %>% 
    kable("html") %>% 
    kable_styling(position = "center")
```

### 3 Loop 

```{r, message=FALSE, fig.width=7}
library(jsonlite)
library(listviewer)

# split to chunks to wrap in JSON
chunks_by_date <- df %>% 
    arrange(date) %>% 
    filter(!is.na(sales)) %>% 
    split(.$date)

# to convert each to a list in recursion
# must pass the dots
from_row_to_list <- function(brand, model, type, sales, ...) {
    list(
        "brand" = brand,
        "model" = model,
        "type"  = type,
        "sales" = sales
    )
}

# to name list in recursion at one go
paste_list_name <- function(brand, model, ...) {
    paste(brand, model)
}

# use map instead of for loop
out <- map(chunks_by_date, ~ {
    l <- pmap(.x, from_row_to_list)
    n <- pmap(.x, paste_list_name)
    set_names(l, n)
})
names(out) <- names(chunks_by_date)

# final result
head(out, 10) %>% listviewer::jsonedit()
```

Done